[project]
name = "stableswap"
authors = []
description = ""
telemetry = false
requirements = []
boot_contracts = ["pox", "costs-v2", "bns"]

[project.cache_location]
path = ".requirements"
[contracts.apple-dex]
path = "contracts/apple-dex.clar"

[contracts.apples-lp]
path = "contracts/apples-lp.clar"

[contracts.apples-r]
path = "contracts/apples-r.clar"

[contracts.fee-escrow]
path = "contracts/fee-escrow.clar"

[contracts.sip-010-trait-ft-standard]
path = "contracts/external/sip-010-trait-ft-standard.clar"

[contracts.stableswap]
path = "contracts/stableswap.clar"

[contracts.trait-stableswap]
path = "contracts/trait-stableswap.clar"

[contracts.usd-lp]
path = "contracts/usd-lp.clar"

[contracts.usda-token]
path = "contracts/external/usda-token.clar"

[contracts.usdex]
path = "contracts/usdex.clar"

[contracts.usdex-lp]
path = "contracts/usdex-lp.clar"

[contracts.xbtc-token]
path = "contracts/xbtc-token.clar"

[contracts.xusd-token]
path = "contracts/external/xusd-token.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
